services:
  dev:
    build:
      context: .
      args:
        MC_VERSION: ${MC_VERSION}
        FORGE_VERSION: ${FORGE_VERSION}
      dockerfile: Dockerfile
    container_name: mc-dev
    env_file: .env
    volumes:
      - mod_build:/usr/local/proj/build/libs
  server:
    container_name: mc-server
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      VERSION: ${MC_VERSION}
      FORGE_VERSION: ${FORGE_VERSION}
    volumes:
      - type: volume
        source: mod_build
        target: /data/mods
        read_only: true
volumes:
  mod_build:
    name: mod-build
