services:
  dev:
    build:
      context: .
      ssh:
        - default
      args:
        MC_VERSION: ${MC_VERSION}
        FORGE_VERSION: ${FORGE_VERSION}
        REPO: ${REPO}
      dockerfile: Dockerfile
    environment:
      MC_VERSION: ${MC_VERSION}
      FORGE_VERSION: ${FORGE_VERSION}
      REPO: ${REPO}
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
    container_name: mc-dev
    volumes:
      - mod_build:/usr/local/proj/build/libs
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
  server:
    container_name: mc-server
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      VERSION: ${MC_VERSION}
      FORGE_VERSION: ${FORGE_VERSION}
    volumes:
      - type: volume
        source: mod_build
        target: /data/mods
        read_only: true
volumes:
  mod_build:
    name: mod-build
